### ISSUE TITLE
Adding an export function

### ISSUE THREAD

**Issue by Kevinrob** [simonpercic/ResponseEcho#15]
Sometimes, it can be nice to export the request for importing it in Postman or runnning it on cURL. We can debugging more easily like that. 👍

**Comment by simonpercic** [comment]
That seems like a good idea @Kevinrob! 

One potential issue I see is that logging of request headers would have to be enabled as well, since otherwise you might not be able to execute the network call again (e.g. if your endpoints require authentication via header tokens). 

If the request headers would be present (or if your endpoints don't need authentication), then it would be possible to generate a cURL command when showing the response info. 👍 

I will add the functionality to my TODO queue, but it might take a while. Feel free to contribute via a pull request to ResponseEcho. 😃
